# Generated by Django 5.2.7 on 2025-10-24 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anecdote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FU', 'Fun facts'), ('RA', 'Rassurante')], default='FU', max_length=2)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion', models.CharField(choices=[('TR', 'Triste'), ('AN', 'Angoissé'), ('AM', 'Amoureux'), ('HE', 'Heureux'), ('CA', 'Calme'), ('ST', 'Stressé'), ('FA', 'Fatigué'), ('AP', 'Apaisé'), ('CO', 'Confiant'), ('IC', 'Incompris'), ('SE', 'Seul'), ('TE', 'En tempête émotionnelle')], max_length=2)),
                ('intensity', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='CESIZen.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteAnecdote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('anecdote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='CESIZen.anecdote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='CESIZen.user')),
            ],
            options={
                'unique_together': {('user', 'anecdote')},
            },
        ),
    ]
